<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <PlatformTarget>AnyCPU</PlatformTarget>
    <!-- Explicitly disable fallback folders in the project itself -->
    <DisableImplicitNuGetFallbackFolder>true</DisableImplicitNuGetFallbackFolder>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FlashCap" Version="1.11.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.3" />
    <PackageReference Include="Microsoft.Extensions.ObjectPool" Version="10.0.3" />
    <PackageReference Include="OpenCvSharp4" Version="4.11.0.20250507" />
    <PackageReference Include="OpenCvSharp4.official.runtime.linux-x64" Version="4.11.0.20250507" />
    <PackageReference Include="QuickNV.Onvif" Version="1.1.0" />
    <PackageReference Include="QuickNV.Onvif.Discovery" Version="1.1.0" />
  </ItemGroup>

</Project>

