<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<PlatformTarget>AnyCPU</PlatformTarget>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="DirectShowLib.Standard" Version="2.1.0" />
    <PackageReference Include="Emgu.CV" Version="4.9.0.5494" />
    <PackageReference Include="Emgu.CV.runtime.windows" Version="4.9.0.5494" />
		<PackageReference Include="FlashCap" Version="1.10.0" />
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.0" />
		<PackageReference Include="QuickNV.Onvif" Version="1.1.0" />
		<PackageReference Include="QuickNV.Onvif.Discovery" Version="1.1.0" />
		<PackageReference Include="System.Text.Json" Version="9.0.0" />
	</ItemGroup>

</Project>
