<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <InvariantGlobalization>true</InvariantGlobalization>
    <UserSecretsId>c8520b94-3f02-47ea-87c6-1e09e737cd2c</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <StartupObject></StartupObject>
    <UseBlazorWebAssembly>true</UseBlazorWebAssembly>
    <OutputType>Exe</OutputType>
    <!-- Explicitly disable fallback folders in the project itself -->
    <DisableImplicitNuGetFallbackFolder>true</DisableImplicitNuGetFallbackFolder>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
    <IsPublishable>True</IsPublishable>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
    <IsPublishable>True</IsPublishable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNet.WebApi.Client" Version="6.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="8.0.17" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.2" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="OpenCvSharp4" Version="4.11.0.20250507" />
    <PackageReference Include="OpenCvSharp4.official.runtime.linux-x64" Version="4.11.0.20250507" />
    <PackageReference Include="OpenCvSharp4.runtime.win" Version="4.11.0.20250507" />
    <PackageReference Include="Serilog" Version="4.3.0" />
    <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
    <PackageReference Include="Serilog.Extensions.Hosting" Version="10.0.0" />
    <PackageReference Include="Serilog.Formatting.Compact" Version="3.0.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.2" />
    <PackageReference Include="Swashbuckle.AspNetCore.Annotations" Version="10.1.2" />
    <PackageReference Include="Swashbuckle.AspNetCore.Newtonsoft" Version="10.1.2" />
    <PackageReference Include="Swashbuckle.AspNetCore.Swagger" Version="10.1.2" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerGen" Version="10.1.2" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" Version="10.1.2" />
    <PackageReference Include="Telegram.Bot" Version="22.8.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BlazorClient\CameraServer.Client.csproj" />
    <ProjectReference Include="..\CameraLib\CameraLib.csproj" />
    <ProjectReference Include="..\Shared\CameraServer.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <None Update="libcvextern.so">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="openh264-1.8.0-win32.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="openh264-1.8.0-win64.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
