<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<!-- Explicitly disable fallback folders in the project itself -->
		<DisableImplicitNuGetFallbackFolder>true</DisableImplicitNuGetFallbackFolder>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="System.ComponentModel.Annotations" Version="5.0.0" />
	</ItemGroup>

	<ItemGroup>
		<SupportedPlatform Include="browser" />
	</ItemGroup>
</Project>

